[build]
  publish = "public" # Change this if `index.html` is not in the `public` directory
  functions = "netlify/functions"

[[redirects]]
  from = "/visit-webhook"
  to = "/.netlify/functions/visit-webhook"
  status = 200

[[redirects]]
  from = "/button-webhook"
  to = "/.netlify/functions/button-webhook"
  status = 200
